version: "3.3"

services:
  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      # You should definitely change the password in production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-user}
      POSTGRES_USER: ${POSTGRES_USER:-user}
    volumes:
      - ./docker/db/data:/var/lib/postgresql/data:rw

  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    environment:
      APP_ENV: ${APP_ENV}
      SYMFONY_VERSION: ${SYMFONY_VERSION:-5.*}
    volumes:
      - .:/usr/src/
      - ./docker/php/custom.ini:/usr/local/etc/php/conf.d/custom.ini
    working_dir: /usr/src

  nginx:
    image: nginx:1.15.3-alpine
    restart: on-failure
    volumes:
      - ./public/:/usr/src/
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php
