version: "3.3"

services:
  adminer:
    image: adminer
    ports:
    - 8080:8080

  node:
    image: node:16
    volumes:
      - .:/home/node/app
    working_dir: /home/node/app
    user: 1000:1000

  nginx:
    ports:
    - 80:80
